/**
 * Database Initialization
 * Combined PRAGMA configuration + table creation.
 * Single source of truth for database setup.
 *
 * This module consolidates:
 * - PRAGMA configuration (from src/lib/db/init.ts)
 * - Table creation (from src/db/index.ts)
 */

import type { IDatabase, DbConfigResult } from './types';
import { getDatabase } from './connection';
import { initialSchema } from './migrations/sql';

/** PRAGMA initialization queries */
const INIT_PRAGMAS = [
  'PRAGMA journal_mode = WAL',
  'PRAGMA foreign_keys = ON',
  'PRAGMA synchronous = NORMAL',
  'PRAGMA cache_size = -64000',
  'PRAGMA temp_store = MEMORY',
];

/**
 * Required tables for verification
 *
 * NOTE (PRE-MORTEM): Only core chat tables are verified here.
 * PARA tables (from src/db/schema/para.ts) are NOT included because:
 * 1. They're created by the same migration SQL (initialSchema)
 * 2. PARA features may not be enabled for all users
 * 3. Verifying chat tables is sufficient to prove init succeeded
 *
 * If PARA functionality breaks, add PARA tables to this list.
 */
const REQUIRED_TABLES = ['conversations', 'messages', 'session_index'];

/**
 * Initialize database with PRAGMAs and tables
 * This is the SINGLE entry point for database initialization.
 */
export async function initializeDatabase(): Promise<DbConfigResult> {
  const db = await getDatabase();
  return initializeDatabaseWithConnection(db);
}

/**
 * Initialize database with provided connection (for testing)
 */
export async function initializeDatabaseWithConnection(db: IDatabase): Promise<DbConfigResult> {
  // Execute PRAGMA statements
  for (const pragma of INIT_PRAGMAS) {
    await db.execute(pragma);
  }

  // Create tables using generated migration SQL
  await createTables(db);

  // Verify configuration
  const [journalResult] = await db.select<{ journal_mode: string }>('PRAGMA journal_mode');
  const [fkResult] = await db.select<{ foreign_keys: number }>('PRAGMA foreign_keys');

  const journalMode = journalResult?.journal_mode ?? 'unknown';
  const foreignKeysEnabled = fkResult?.foreign_keys === 1;

  // Verify tables exist
  const tables = await db.select<{ name: string }>(
    `SELECT name FROM sqlite_master WHERE type='table' AND name IN (${REQUIRED_TABLES.map(() => '?').join(',')})`,
    REQUIRED_TABLES
  );

  const tablesCreated = tables.map(t => t.name);
  const missingTables = REQUIRED_TABLES.filter(t => !tablesCreated.includes(t));

  if (missingTables.length > 0) {
    throw new Error(`Database init incomplete. Missing tables: ${missingTables.join(', ')}`);
  }

  console.log('[DB] Database initialized:', {
    journalMode,
    foreignKeysEnabled,
    tablesCreated,
  });

  return {
    walEnabled: journalMode.toLowerCase() === 'wal',
    foreignKeysEnabled,
    journalMode,
    tablesCreated,
  };
}

/**
 * Create all tables using generated migration SQL
 * Single source of truth: imports from migrations/sql.ts (auto-generated by drizzle-kit)
 */
async function createTables(db: IDatabase): Promise<void> {
  const statements = initialSchema
    .split('--> statement-breakpoint')
    .map((s) => s.trim())
    .filter((s) => s.length > 0);

  for (const stmt of statements) {
    // Add IF NOT EXISTS for idempotency
    const idempotentStmt = stmt
      .replace(/CREATE TABLE `/g, 'CREATE TABLE IF NOT EXISTS `')
      .replace(/CREATE INDEX `/g, 'CREATE INDEX IF NOT EXISTS `');
    await db.execute(idempotentStmt);
  }
}

/**
 * Verify database configuration meets requirements
 */
export function verifyConfig(config: DbConfigResult): { valid: boolean; errors: string[] } {
  const errors: string[] = [];

  if (!config.walEnabled) {
    errors.push(`WAL mode not enabled. Current mode: ${config.journalMode}`);
  }

  if (!config.foreignKeysEnabled) {
    errors.push('Foreign keys not enabled');
  }

  if (config.tablesCreated.length < REQUIRED_TABLES.length) {
    const missing = REQUIRED_TABLES.filter(t => !config.tablesCreated.includes(t));
    errors.push(`Missing tables: ${missing.join(', ')}`);
  }

  return {
    valid: errors.length === 0,
    errors,
  };
}
