#!/bin/bash
# ============================================
# Burn-In Script for Flaky Test Detection
# ============================================
# Runs tests multiple times to detect non-deterministic failures
# Generated by TEA CI workflow - 2026-01-24
#
# Usage:
#   ./scripts/burn-in.sh          # Default 10 iterations
#   ./scripts/burn-in.sh 5        # Custom iterations
#   ./scripts/burn-in.sh 100      # High-confidence mode
#
# ============================================

set -e

ITERATIONS=${1:-10}
FAILED=0

echo ""
echo "=========================================="
echo "  Burn-In: $ITERATIONS Iterations"
echo "=========================================="
echo ""

for i in $(seq 1 $ITERATIONS); do
  echo "[$i/$ITERATIONS] Running tests..."

  if npm run test:e2e > /dev/null 2>&1; then
    echo "  PASS"
  else
    echo "  FAIL"
    FAILED=$((FAILED + 1))
  fi
done

echo ""
echo "=========================================="
echo "  Results: $((ITERATIONS - FAILED))/$ITERATIONS passed"
echo "=========================================="

if [[ $FAILED -gt 0 ]]; then
  echo ""
  echo "WARNING: $FAILED failures detected - tests may be flaky"
  echo "Review test-results/ for failure details"
  exit 1
fi

echo ""
echo "SUCCESS: No flakiness detected"
