#!/bin/bash
# ============================================
# Local CI Mirror Script
# ============================================
# Mirrors the CI pipeline locally for debugging
# Generated by TEA CI workflow - 2026-01-24
#
# Usage:
#   ./scripts/ci-local.sh         # Full pipeline
#   ./scripts/ci-local.sh --quick # Skip burn-in
#
# ============================================

set -e  # Exit on first error

QUICK_MODE=false
if [[ "$1" == "--quick" ]]; then
  QUICK_MODE=true
fi

echo ""
echo "=========================================="
echo "  Orion Butler - Local CI Pipeline"
echo "=========================================="
echo ""

# Stage 1: Lint
echo "[1/4] Running ESLint..."
npm run lint || {
  echo "FAIL: ESLint errors detected"
  exit 1
}
echo "PASS: Lint stage complete"
echo ""

# Stage 2: Type Check
echo "[2/4] Running Type Check..."
npx tsc --noEmit || {
  echo "FAIL: TypeScript errors detected"
  exit 1
}
echo "PASS: Type check complete"
echo ""

# Stage 3: Unit Tests
echo "[3/4] Running Unit Tests..."
npm run test:unit || {
  echo "FAIL: Unit test failures"
  exit 1
}
echo "PASS: Unit tests complete"
echo ""

# Stage 4: E2E Tests
echo "[4/4] Running E2E Tests..."
npm run test:e2e || {
  echo "FAIL: E2E test failures"
  exit 1
}
echo "PASS: E2E tests complete"
echo ""

# Optional: Burn-in (reduced iterations)
if [[ "$QUICK_MODE" == "false" ]]; then
  echo "[Burn-in] Running 3 iterations..."
  for i in {1..3}; do
    echo "  Iteration $i/3..."
    npm run test:e2e || {
      echo "FAIL: Burn-in failed on iteration $i"
      exit 1
    }
  done
  echo "PASS: Burn-in complete"
  echo ""
fi

echo "=========================================="
echo "  LOCAL CI PIPELINE PASSED"
echo "=========================================="
echo ""
