#!/bin/bash
# ============================================
# Selective Test Execution
# ============================================
# Runs only tests affected by changed files
# Generated by TEA CI workflow - 2026-01-24
#
# Usage:
#   ./scripts/test-changed.sh           # Compare with HEAD~1
#   ./scripts/test-changed.sh main      # Compare with main branch
#
# ============================================

set -e

COMPARE_REF=${1:-HEAD~1}

echo ""
echo "=========================================="
echo "  Selective Test Execution"
echo "  Comparing with: $COMPARE_REF"
echo "=========================================="
echo ""

# Get changed files
CHANGED_FILES=$(git diff --name-only "$COMPARE_REF" 2>/dev/null || git diff --name-only HEAD~1)

echo "Changed files:"
echo "$CHANGED_FILES" | sed 's/^/  /'
echo ""

# Check if src/ files changed
if echo "$CHANGED_FILES" | grep -q "^src/"; then
  echo "Source files changed - running full test suite..."
  npm run test:e2e
elif echo "$CHANGED_FILES" | grep -q "^tests/"; then
  echo "Test files changed - running affected tests..."
  # Extract test file paths
  TEST_FILES=$(echo "$CHANGED_FILES" | grep "^tests/" | tr '\n' ' ')
  npm run test:e2e -- $TEST_FILES
else
  echo "No test-affecting changes detected"
  echo "Skipping test execution"
fi

echo ""
echo "=========================================="
echo "  Selective Testing Complete"
echo "=========================================="
